export const defaultStrings = {
  summary: "A passionate software engineer with a keen interest in developing efficient and scalable applications.",
  firstName: "Emily",
  lastName: "Johnson",
  dateOfBirth: "1995-07-15",
  email: "emily.johnson@example.com",
  phoneNumber: "+1 415 555 0178",
  jobPosition: "Software Engineer",
  company: "Tech Solutions Inc.",
  jobExperienceFromDate: "2018-03-01",
  jobExperienceToDate: "2022-09-15",
  responsibilities: "Developed and maintained web applications, collaborated with cross-functional teams to define project requirements, and implemented new features.",
  fieldOfStudy: "Computer Science",
  institution: "University of California, Berkeley",
  educationFromDate: "2013-08-20",
  educationToDate: "2017-05-15",
};
